name: CI Workflow Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Mengambil kode dari repositori
      uses: actions/checkout@v4

    - name: Menjalankan skrip pengujian sederhana
      run: echo "Proses otomatisasi integrasi (CI) berhasil dijalankan!"
